spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql : true
    generate-ddl: false # jpa 의 하위속성이다.
#  generate-ddl: true 하면 자동으로 entity 에서 사용하고 있는 태이블들을 생성해주는 옵션이다.
    hibernate:
      ddl-auto: create-drop # 생성하고 persistance context 가 종료될때 자동으로 드랍하는 옵션
                # none ddl-auto 실행하지않는것
                # create 항상 새로 생성하는 옵션
                # create 은 persistance context 를 띄울때 앞 쪽에서 drop 을 하고 create 를 하는데
                # create-drop 은 persistnace context 를 띄울때 생성하고 종료할때 drop 한다.
                # validate : 단순 비교작업만하고 entity 설정과 스키마가 서로다른 부분이 확인대면 오류를 발생시킨다.
                # update : 실제 스키마와 엔티티 클래스를 비교를해서 변경에대한부분만 반영한다. 즉 드랍을 하지 않는다.


  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    password: 1234
    initialization-mode: always # 이렇게 지정하면 스프링에서 지정하는 initialization mode 가 동작한다는 의미이다.

server:
  port: 8070

# generate-ddl : false
# ddl-auto : none 으로하면  spring-boot 문서에는 ddl-auto 가 더 세밀한 요소여서
# generate-ddl 를 무시한다고 되있다. ddl-auto 옵션이더 우선적으로 실행된다.

# 스키마.sql 이있는상태에서 ddl-auto : create-drop 이되면 충돌되서 무시된다.
# initialization-mode : always 가 먼저된다.

logging:
  level:
    root: trace